### ISSUE TITLE
Pip Installation does not work

### ISSUE THREAD

**Issue by VRSandeep** [razorpay/razorpay-python#1]
`pip install razorpay` throws 
```
Could not find a version that satisfies the requirement razorpay (from versions: )
No matching distribution found for razorpay
```

**Comment by shashankkumar** [comment]
@captn3m0 take a look?

**Comment by captn3m0** [comment]
This has now been fixed. Thanks a lot :+1:

**Comment by VRSandeep** [comment]
Although pip install ran, it did not install resources folder

**Comment by captn3m0** [comment]
Sorry about that. Just pushed a new release (0.1.1) with the fix.

**Comment by VRSandeep** [comment]
Could you please check again

**Comment by captn3m0** [comment]
The file at pypi is https://pypi.python.org/packages/source/r/razorpay/razorpay-0.1.1.tar.gz

which contains the razorpay/resources subdirectory. I am able to make requests fine using the test code with this.

**Comment by captn3m0** [comment]
Could you try uninstalling and re-installing the package?

**Comment by pnhegde** [comment]
Manually running `setup.py install` works but `pip install razorpay` still not working. Create a new virtualenv and test it. You may want to check this out. http://tom-christie.github.io/articles/pypi/

**Comment by VRSandeep** [comment]
Can you move files from resources folder to the same folder as a quick fix?

**Comment by captn3m0** [comment]
@pnhegde Thanks for the link. Learnt a lot about python packaging today.

The problem was indeed in setup.py, which doesn't work recursively. I have added the resources module to it now, and its being imported perfectly as well

```
mkvirtualenv rzp-testing

Using base prefix '/usr'
New python executable in rzp-testing/bin/python3
Also creating executable in rzp-testing/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /home/nemo/.virtualenvs/rzp-testing/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/nemo/.virtualenvs/rzp-testing/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/nemo/.virtualenvs/rzp-testing/bin/preactivate
virtualenvwrapper.user_scripts creating /home/nemo/.virtualenvs/rzp-testing/bin/postactivate
virtualenvwrapper.user_scripts creating /home/nemo/.virtualenvs/rzp-testing/bin/get_env_details

pip install razorpay

Collecting razorpay
  Downloading razorpay-0.1.2.tar.gz
Collecting requests (from razorpay)
  Using cached requests-2.9.0-py2.py3-none-any.whl
Building wheels for collected packages: razorpay
  Running setup.py bdist_wheel for razorpay
  Stored in directory: /home/nemo/.cache/pip/wheels/aa/73/92/b81235725ac4e08957b095d85659d970a5f7fd1905a46ef80d
Successfully built razorpay
Installing collected packages: requests, razorpay
Successfully installed razorpay-0.1.2 requests-2.9.0

python

Python 3.5.1 (default, Dec  7 2015, 12:58:09) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import razorpay.resources
>>> razorpay.resources
<module 'razorpay.resources' from '/home/nemo/projects/work/razorpay/razorpay-python/razorpay/resources/__init__.py'>
>>> import razorpay
>>> razorpay
<module 'razorpay' from '/home/nemo/projects/work/razorpay/razorpay-python/razorpay/__init__.py'>
>>> razorpay.resources
<module 'razorpay.resources' from '/home/nemo/projects/work/razorpay/razorpay-python/razorpay/resources/__init__.py'>

>>> 
```

**Comment by msj2** [comment]
Hi, 
I'm on Ubuntu 16.04
python 2.7.12
pip 9.0.1

sudo pip install razorpay throws Error. Trys 4 times

Pasting the pip error log below.


`Collecting razorpay
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2243c15c50>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /packages/a6/15/20ec9a2bdc11496a689c660c696399e1a5488c47fbfde2f8e9cb1a958ae1/razorpay-1.1.1.tar.gz
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2243c15710>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /packages/a6/15/20ec9a2bdc11496a689c660c696399e1a5488c47fbfde2f8e9cb1a958ae1/razorpay-1.1.1.tar.gz
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2243c15490>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /packages/a6/15/20ec9a2bdc11496a689c660c696399e1a5488c47fbfde2f8e9cb1a958ae1/razorpay-1.1.1.tar.gz
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2243c20b50>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /packages/a6/15/20ec9a2bdc11496a689c660c696399e1a5488c47fbfde2f8e9cb1a958ae1/razorpay-1.1.1.tar.gz
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2243c20e50>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /packages/a6/15/20ec9a2bdc11496a689c660c696399e1a5488c47fbfde2f8e9cb1a958ae1/razorpay-1.1.1.tar.gz
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 853, in _download_http_url
    stream=True,
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/a6/15/20ec9a2bdc11496a689c660c696399e1a5488c47fbfde2f8e9cb1a958ae1/razorpay-1.1.1.tar.gz (Caused by NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2243c20890>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
`

Looking fwd to resolution.

**Comment by captn3m0** [comment]
@msj2 Are you able to install other packages fine? Looks like a network issue:

```
NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2243c20890>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
```

**Comment by Krishnaraj-K** [comment]
Hey Msj, 

@msj2 Did you solve the issue, if yes could you please do let me know how to fixed it, i am also facing the same issue exactly like you, even i can tell this is a network issue, require your help if fixed.
