### ISSUE TITLE
Behaviour Not Clear

### ISSUE THREAD

**Issue by adhibhuta** [razorpay/razorpay-python#106]
This is how I am verifying the webhook-
`client.utility.verify_webhook_signature(request.body.decode('utf-8'), request.headers['x-razorpay-signature'], RZP_SECRET)`

I assumed it would return a boolean because [this](https://github.com/razorpay/razorpay-python/blob/a7717df7cc7ab59a97cb56113a244f7685e443a0/razorpay/utility/utility.py#L46) returns the result object, but somehow this is returning only a `None` or throwing an exception so I wrapped it around `try-except`, just wondering if that's the right thing to do or it should return a boolean in a normal scenario.

**Comment by adhibhuta** [comment]
@captn3m0 Any updates on this? Is this the right behavior?

**Comment by ankitdas13** [comment]
@adhibhuta We apologize for the delay, as well as for this issue. It has already been fixed in #67. Could you please update the most recent version to resolve this issue? 
<img width="799" alt="Screenshot 2022-11-24 at 4 09 55 PM" src="https://user-images.githubusercontent.com/89454448/203763963-adb2557d-0734-42a2-9557-dec0fe8fa077.png">

I have added the code snippet for your reference

**Comment by ankitdas13** [comment]
Closing this issue for now, due to not getting any response. If you are still facing this same issue, please update to the most recent version to resolve this issue. If you need any help then please let us know.
