### ISSUE TITLE
 The id provided does not exist any idea?

### ISSUE THREAD

**Issue by rahul6612** [razorpay/razorpay-python#126]
while creating the new payment i am passing the order_id like this 
`payment = client.order.create(dict(amount=order_amount, currency=order_currency, order_id=product_order_id))`
and in HTML i am doing this   `data-order_id= {{product_order_id}}` but during payment why its showing  **_The id provided does not exist_**  i am using in test mode.

**Comment by ankitdas13** [comment]
@rahul6612 Apologise for the long delay. Seems like the order id is not generating before checkout, that's why you're getting this error . For anyone else who is searching, if you are experiencing this issue while checking out then you can try with static order id instead of dynamic, if it works, then there would be an issue in your function where order id is generating

**Comment by ankitdas13** [comment]
Closing this issue for now, due to not getting any response. If you need any help then please let us know.
