### ISSUE TITLE
Payment Link API not available in tag 1.2.0

### ISSUE THREAD

**Issue by noufal-onsite** [razorpay/razorpay-python#151]
We are not able to see payment link api on tag 1.2.0, When we trying to use it via pip always getting non payment link versions

**Comment by ankitdas13** [comment]
@noufal-onsite Apologise for the long delay. Could you please let us know if this issue has been resolved? 
In case someone gets an error while using the `payment_link` API, please check this [doc](https://github.com/razorpay/razorpay-python/blob/master/documents/paymentLink.md)

**Comment by ankitdas13** [comment]
Closing this issue for now, due to not getting any response. If someone is still facing this same issue, please update to the most recent version to resolve this issue or you can check this [doc](https://github.com/razorpay/razorpay-python/blob/master/documents/paymentLink.md) for more details. If you need any help then please let us know.
