### ISSUE TITLE
Capturing payment on test credentials throws error

### ISSUE THREAD

**Issue by arpansac** [razorpay/razorpay-python#56]
This is what I'm getting

```
client.payment.capture(payment_id, str(amount))

*** requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
```

**Comment by kaliaabhishek** [comment]
Hi @arpansac ,

As far as I can understand the exception, it's more likely an issue on your server side (SSL versioning) and the python requests module rather than an issue with this repository. However, can you share the output of these commands on your terminal?

`python -c "import ssl; print ssl.OPENSSL_VERSION"`

`python -c "from OpenSSL.SSL import SSLeay_version, SSLEAY_VERSION; print SSLeay_version(SSLEAY_VERSION)"`

**Comment by arpansac** [comment]
Hey @kaliaabhishek 
Found the solution, actually pip3 is unable to install anything as it is unable to access the internet (visible in logs). There's a module which got changed after Python 3.5. So, the solution is to rollback my system's python to a version before 3.5. 

Should there be a support in the Razorpay package too?

**Comment by kaliaabhishek** [comment]
Hi @arpansac ,

Glad you found the solution to your problem.

The current package seems compatible with ~3.5, your problem might be an isolated local problem. I will try reproducing your error nonetheless.

**Comment by harman28** [comment]
Closing, unrelated to package.

**Comment by AditSoni** [comment]
having the same error ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

and this appears randomly , during using create order api or refund api , using python version 3.9.12 and razorpay  python package 1.3.0 , 
let me know if you guys found a fix

**Comment by garyspx** [comment]
@AditSoni were you able to find the fix?

**Comment by AditSoni** [comment]
> @AditSoni were you able to find the fix?

Not a fix but a work around by putting it in try and except block, and setting max retries(via a for loop) to 3 .
