### ISSUE TITLE
Send/Resend Notifications

### ISSUE THREAD

**Issue by varunajmera0** [razorpay/razorpay-python#60]
There is no implementation to resend the notification.

https://razorpay.com/docs/invoices/api/#sendresend-notifications

**Comment by ankitdas13** [comment]
@varunajmera0 Apologise for the long delay. It has already been added in one of recent releases. Check this [doc](https://razorpay.com/docs/api/payments/invoices/#send-notifications) for your reference. It would be helpful if you let us know if this issue has been resolved or not ?

**Comment by ankitdas13** [comment]
Thanks for reporting this issue. It has already been fixed in [v1.3.0](https://github.com/razorpay/razorpay-python/releases/tag/1.3.0) releases 🚀. Please update to the [v1.3.1](https://github.com/razorpay/razorpay-python/releases/tag/v1.3.1) version to resolve this issue. If the issue still persists after upgrading, please feel free to re-open this issue.

Closing for now.
