### ISSUE TITLE
Signature verification for subscription giving key error

### ISSUE THREAD

**Issue by GopikrishnanSasikumar** [razorpay/razorpay-python#82]
```
KeyError: 'razorpay_order_id'

```

Getting this while trying to verify signature of subscription using client.utility.verify_payment_signature()

Is this available only for orders ?

**Comment by harman28** [comment]
Yes, only available for orders now, we should upgrade this to handle subscriptions as well. Noted. For now, you'll need to write the verify function yourself (can copy the existing source), till we do another release.

**Comment by pupattan** [comment]
@harman28 

Even i provide subscription_id as razorpay_order_id. But still verification is failing.
it does pining like this : sub_FOYXLP0SgUIamT|pay_FOYZSM6AqMr76R

**Comment by ashutoshsingh0223** [comment]
Yes that is what is wrong. If you flip it starts to work Eg. pay_FOYZSM6AqMr76R|sub_FOYXLP0SgUIamT

**Comment by ankitdas13** [comment]
Thanks for reporting this issue. It has already been fixed in [v1.3.0](https://github.com/razorpay/razorpay-python/releases/tag/1.3.0) releases 🚀. Please update to the [v1.3.1](https://github.com/razorpay/razorpay-python/releases/tag/v1.3.1) version to resolve this issue. If the issue still persists after upgrading, please feel free to re-open this issue.

Closing for now.
