### ISSUE TITLE
How to update a subscription using the python library

### ISSUE THREAD

**Issue by Srikeerthan20** [razorpay/razorpay-python#85]
Below is th e sample curl code for updating a subscription:

`curl -u <YOUR_KEY>:<YOUR_SECRET> \-X PATCH https://api.razorpay.com/v1/subscriptions/sub_00000000000001 \-H "Content-Type: application/json" \-d '{  "plan_id":"plan_00000000000002",  "quantity":5,  "remaining_count":5,  "start_at":1496000432,  "schedule_change_at":"now",  "customer_notify":1}'`

**Comment by ankitdas13** [comment]
@Srikeerthan20 My apologies for the long delay. i hope this issue has been resolved , The SDK has also been updated with code snippets of all APIs please check this [doc ](https://github.com/razorpay/razorpay-python/tree/master/documents) for more details

**Comment by ankitdas13** [comment]
It has already been fixed in [v1.3.0](https://github.com/razorpay/razorpay-python/releases/tag/1.3.0) releases 🚀. Please update to the [v1.3.1 ](https://github.com/razorpay/razorpay-python/releases/tag/v1.3.1)version to resolve this issue. If the issue still persists after upgrading, please feel free to re-open this issue.
