### ISSUE TITLE
fund account should be array (bad request error)

### ISSUE THREAD

**Issue by siddanand** [razorpay/razorpay-python#89]
while making a payout using composite api i am getting this error and i cannot find any solution to this on the web pls help

**Comment by ankitdas13** [comment]
@siddanand Apologise for the long delay . Your account didn't have access to this feature, which is why you received this error.  If someone else who experiencing this issue , you have to enable this feature, you will need to contact [support](https://razorpay.com/support/) or use the chat option on your merchant dashboard.

**Comment by ankitdas13** [comment]
Closing this issue for now, due to not getting any response. If you are still facing this same issue, please contact [support](https://razorpay.com/support/) or use the chat option on your merchant dashboard to enable this feature. If you need any help then please let us know.
